name: Maven Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Matches tags in the form 3.3.0

jobs:
  maven-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      WORKSPACE: "${{ github.workspace }}"
      GIT_BRANCH: "${{ github.ref }}"
      CURRENT_TAG: "${{ github.ref_name }}"
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      PGP_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
      GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
    steps:
    - name: Set up Git
      run: git config --global --add safe.directory '*'
      
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install GPG
      run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
    
    - name: Import GPG Private Key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
        gpg --batch --import private.key
        rm private.key

    - name: Trust GPG Key
      run: |
        KEY_ID=$(gpg --list-keys --with-colons | grep pub | cut -d: -f5)
        echo -e "trust\n5\ny\nquit" | gpg --batch --yes --command-fd 0 --edit-key $KEY_ID

    - name: Verify AAR Presence
      run: |
        if [ ! -f "./approov-sdk/approov-sdk.aar" ]; then
          echo "Error: ./approov-sdk/approov-sdk.aar not found!"
          exit 1
        fi

    - name: Create Package
      run: cd .maven && ./build-and-sign.sh

    - name: Publish Package
      run: cd .maven && ./maven-publish.sh
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: approov-sdk-artifact-${{ github.ref_name }}
        path: approov-sdk.aar
